apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            location / {
                default_type text/html;
                return 200 '<html><body bgcolor="grey"><h1 style="font-size: 48px; font-weight: bold; color: blue">Hello, we are learning DevOPS practices!</h1></body></html>';
                add_header Content-Type text/plain;
            }
        }
    }
