apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-prod
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: wordpress-prod
    tier: mysql
  ports:
    - port: 3306
      targetPort: 3306
