apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-prod
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-prod
  hostPath:
    path: "/mnt/data/mysql-prod" # Ensure this path exists on all nodes
