apiVersion: v1
kind: Service
metadata:
  name: wordpress-service-prod
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: wordpress-prod
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
