apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-prod
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app: wordpress-prod
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress-prod
        tier: frontend
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpress.db.host }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.db.user }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass-prod
                  key: password
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.db.name }}
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
